# Form implementation generated from reading ui file '.\uis\choose_number_people.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(281, 205)
        Dialog.setStyleSheet("QDialog {\n"
"    background-color: rgb(255, 255, 243)\n"
"}")
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(-70, 160, 301, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.spinbox_adult = QtWidgets.QSpinBox(parent=Dialog)
        self.spinbox_adult.setGeometry(QtCore.QRect(180, 30, 61, 31))
        self.spinbox_adult.setMaximum(30)
        self.spinbox_adult.setObjectName("spinbox_adult")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(40, 30, 141, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 70, 141, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(40, 110, 141, 31))
        self.label_3.setObjectName("label_3")
        self.spinbox_child = QtWidgets.QSpinBox(parent=Dialog)
        self.spinbox_child.setGeometry(QtCore.QRect(180, 70, 61, 31))
        self.spinbox_child.setMaximum(30)
        self.spinbox_child.setObjectName("spinbox_child")
        self.spinbox_rooms = QtWidgets.QSpinBox(parent=Dialog)
        self.spinbox_rooms.setGeometry(QtCore.QRect(180, 110, 61, 31))
        self.spinbox_rooms.setMaximum(30)
        self.spinbox_rooms.setObjectName("spinbox_rooms")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Выберите"))
        self.label.setText(_translate("Dialog", "Сколько взрослых?"))
        self.label_2.setText(_translate("Dialog", "Сколько детей?"))
        self.label_3.setText(_translate("Dialog", "Сколько номеров?"))
