# Form implementation generated from reading ui file '.\hotel_description.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(642, 453)
        Form.setWindowTitle("")
        Form.setStyleSheet("QWidget#Form {\n"
                           "    background-color:rgb(255, 255, 243);\n"
                           "}\n"
                           "\n"
                           "QPushButton {\n"
                           "    background-color: rgb(255, 236, 197);\n"
                           "    font-family: Segoe UI;\n"
                           "    border: none;\n"
                           "    border-radius: 5px;\n"
                           "}\n"
                           "\n"
                           "QPushButton:hover{\n"
                           "    background-color: rgb(255, 215, 199);\n"
                           "    font-weight: 500;\n"
                           "}\n"
                           "QLabel {\n"
                           "    font-family: Segoe UI;\n"
                           "    font-size: 16px;\n"
                           "}\n"
                           "\n"
                           "QTextEdit {\n"
                           "    font-family: Segoe UI;\n"
                           "    font-size: 14px;\n"
                           "}\n"
                           "QComboBox{\n"
                           "    background-color: rgb(255, 236, 197);\n"
                           "    border: none;\n"
                           "    border-radius: 5px;\n"
                           "}\n"
                           "\n"
                           "QLabel#label_name {\n"
                           "    font-weight: 500;\n"
                           "}\n"
                           "\n"
                           "QPushButton#btn_photo_left {\n"
                           "    background-color: transparent;\n"
                           "}\n"
                           "QPushButton#btn_photo_left:hover {\n"
                           "    background-color: rgb(255, 215, 199);\n"
                           "    font-weight: 500;\n"
                           "}\n"
                           "QPushButton#btn_photo_right {\n"
                           "    background-color: transparent;\n"
                           "}\n"
                           "QPushButton#btn_photo_right:hover {\n"
                           "    background-color: rgb(255, 215, 199);\n"
                           "    font-weight: 500;\n"
                           "}")
        self.photo = QtWidgets.QLabel(parent=Form)
        self.photo.setGeometry(QtCore.QRect(50, 20, 281, 171))
        self.photo.setObjectName("photo")
        self.label_name = QtWidgets.QLabel(parent=Form)
        self.label_name.setGeometry(QtCore.QRect(390, 10, 181, 41))
        self.label_name.setObjectName("label_name")
        self.description = QtWidgets.QTextEdit(parent=Form)
        self.description.setGeometry(QtCore.QRect(30, 220, 581, 151))
        self.description.setObjectName("description")
        self.description.setReadOnly(True)
        self.btn_book = QtWidgets.QPushButton(parent=Form)
        self.btn_book.setGeometry(QtCore.QRect(420, 400, 171, 41))
        self.btn_book.setObjectName("btn_book")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(390, 80, 191, 21))
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(parent=Form)
        self.comboBox.setGeometry(QtCore.QRect(390, 120, 221, 41))
        self.comboBox.setObjectName("comboBox")
        self.btn_photo_left = QtWidgets.QPushButton(parent=Form)
        self.btn_photo_left.setGeometry(QtCore.QRect(10, 100, 31, 31))
        self.btn_photo_left.setStyleSheet("")
        self.btn_photo_left.setObjectName("btn_photo_left")
        self.btn_photo_right = QtWidgets.QPushButton(parent=Form)
        self.btn_photo_right.setGeometry(QtCore.QRect(340, 100, 31, 31))
        self.btn_photo_right.setStyleSheet("")
        self.btn_photo_right.setObjectName("btn_photo_right")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(250, 190, 171, 21))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        self.photo.setText(_translate("Form", "ФОто"))
        self.label_name.setText(_translate("Form",
                                           "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Название</span></p></body></html>"))
        self.btn_book.setText(_translate("Form", "Забронировать"))
        self.label.setText(_translate("Form",
                                      "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Доступные номера</span></p></body></html>"))
        self.btn_photo_left.setText(_translate("Form", "<"))
        self.btn_photo_right.setText(_translate("Form", ">"))
        self.label_2.setText(_translate("Form",
                                        "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Описание</span></p></body></html>"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
