# Form implementation generated from reading ui file '.\uis\profile.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(459, 727)
        Form.setWindowTitle("")
        Form.setStyleSheet("QWidget {\n"
"    background-color: rgb(255, 255, 243);\n"
"}\n"
"\n"
"QLabel {\n"
"    font-family: Segoe UI;\n"
"    background-color:rgba(255, 241, 203, 0.8)\n"
"}\n"
"\n"
"QLabel#label_text {\n"
"    font-size: 16px;\n"
"    font-weight: 500;\n"
"}\n"
"\n"
"QLabel#label_9 {\n"
"    font-size:14px;\n"
"}\n"
"\n"
"QLabel#label_10 {\n"
"    font-size:14px;\n"
"}\n"
"\n"
"QPushButton#btn_change {\n"
"    font-size: 14px;\n"
"    background-color: rgba(255, 241, 203, 0.5);\n"
"    border: none;\n"
"    border-radius: 5px\n"
"}\n"
"\n"
"QPushButton#btn_change:hover{\n"
"    background-color: rgba(255, 227, 192, 0.8);\n"
"    color: rgb(67, 63, 58);\n"
"}")
        self.btn_change = QtWidgets.QPushButton(parent=Form)
        self.btn_change.setGeometry(QtCore.QRect(310, 30, 111, 41))
        self.btn_change.setObjectName("btn_change")
        self.label_photo = QtWidgets.QLabel(parent=Form)
        self.label_photo.setGeometry(QtCore.QRect(170, 40, 80, 80))
        self.label_photo.setStyleSheet("background-color: transparent;")
        self.label_photo.setText("")
        self.label_photo.setObjectName("label_photo")
        self.label_text_2 = QtWidgets.QLabel(parent=Form)
        self.label_text_2.setGeometry(QtCore.QRect(100, 130, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_text_2.setFont(font)
        self.label_text_2.setObjectName("label_text_2")
        self.label_FIO = QtWidgets.QLabel(parent=Form)
        self.label_FIO.setGeometry(QtCore.QRect(100, 200, 210, 35))
        self.label_FIO.setObjectName("label_FIO")
        self.label_phone = QtWidgets.QLabel(parent=Form)
        self.label_phone.setGeometry(QtCore.QRect(100, 260, 210, 35))
        self.label_phone.setObjectName("label_phone")
        self.label_email = QtWidgets.QLabel(parent=Form)
        self.label_email.setGeometry(QtCore.QRect(100, 320, 210, 35))
        self.label_email.setObjectName("label_email")
        self.label_9 = QtWidgets.QLabel(parent=Form)
        self.label_9.setGeometry(QtCore.QRect(140, 380, 141, 21))
        self.label_9.setObjectName("label_9")
        self.all_books = QtWidgets.QTableWidget(parent=Form)
        self.all_books.setGeometry(QtCore.QRect(20, 410, 410, 291))
        self.all_books.setObjectName("all_books")
        self.all_books.setColumnCount(0)
        self.all_books.setRowCount(0)
        self.label_books = QtWidgets.QLabel(parent=Form)
        self.label_books.setGeometry(QtCore.QRect(110, 530, 211, 51))
        self.label_books.setStyleSheet("background-color: transparent;\n"
"font-size: 16px;\n"
"")
        self.label_books.setText("")
        self.label_books.setObjectName("label_books")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        self.btn_change.setText(_translate("Form", "Изменить"))
        self.label_text_2.setText(_translate("Form", "<html><head/><body><p align=\"center\">Личные данные</p></body></html>"))
        self.label_FIO.setText(_translate("Form", "<html><head/><body><p align=\"center\">ФИО</p></body></html>"))
        self.label_phone.setText(_translate("Form", "<html><head/><body><p align=\"center\">телефон</p></body></html>"))
        self.label_email.setText(_translate("Form", "<html><head/><body><p align=\"center\">почта</p></body></html>"))
        self.label_9.setText(_translate("Form", "Мои брони:"))
