# Form implementation generated from reading ui file '.\uis\register.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(506, 461)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(506, 319))
        Form.setMaximumSize(QtCore.QSize(506, 12313))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        Form.setFont(font)
        Form.setStyleSheet("QWidget {\n"
"    background-color: rgb(255, 255, 243);\n"
"}\n"
"QLineEdit {\n"
"    background-color: rgb(255, 236, 197);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(255, 236, 197)\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 218, 180)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:transparent;\n"
"}")
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Form)
        self.buttonBox.setGeometry(QtCore.QRect(150, 390, 171, 41))
        self.buttonBox.setStyleSheet("")
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(250, 20, 209, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.email_edit = QtWidgets.QLineEdit(parent=Form)
        self.email_edit.setGeometry(QtCore.QRect(250, 70, 209, 31))
        self.email_edit.setObjectName("email_edit")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(30, 130, 209, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.psw_edit = QtWidgets.QLineEdit(parent=Form)
        self.psw_edit.setGeometry(QtCore.QRect(30, 200, 209, 31))
        self.psw_edit.setObjectName("psw_edit")
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setGeometry(QtCore.QRect(240, 130, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.phone_edit = QtWidgets.QLineEdit(parent=Form)
        self.phone_edit.setGeometry(QtCore.QRect(250, 200, 209, 31))
        self.phone_edit.setObjectName("phone_edit")
        self.edit_surname = QtWidgets.QLineEdit(parent=Form)
        self.edit_surname.setGeometry(QtCore.QRect(250, 310, 209, 31))
        self.edit_surname.setObjectName("edit_surname")
        self.edit_name = QtWidgets.QLineEdit(parent=Form)
        self.edit_name.setGeometry(QtCore.QRect(30, 310, 209, 31))
        self.edit_name.setObjectName("edit_name")
        self.label_5 = QtWidgets.QLabel(parent=Form)
        self.label_5.setGeometry(QtCore.QRect(240, 240, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=Form)
        self.label_6.setGeometry(QtCore.QRect(30, 240, 209, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=Form)
        self.label_7.setGeometry(QtCore.QRect(30, 20, 209, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.name_edit = QtWidgets.QLineEdit(parent=Form)
        self.name_edit.setGeometry(QtCore.QRect(30, 70, 209, 31))
        self.name_edit.setObjectName("name_edit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Регистрация"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\">Введите почту</p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p align=\"center\">Введите пароль</p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p align=\"center\">Введите номер телефона</p></body></html>"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p align=\"center\">Введите фамилию</p></body></html>"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p align=\"center\">Введите имя</p></body></html>"))
        self.label_7.setText(_translate("Form", "<html><head/><body><p align=\"center\">Введите логин</p></body></html>"))
